# permissions for end users to edit nimbleoptiadapters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nimbleoptiadapter-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bbb
    app.kubernetes.io/part-of: bbb
    app.kubernetes.io/managed-by: kustomize
  name: nimbleoptiadapter-editor-role
rules:
- apiGroups:
  - nimbleoptiadapter.nimble-opti-adapter.example.com
  resources:
  - nimbleoptiadapters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nimbleoptiadapter.nimble-opti-adapter.example.com
  resources:
  - nimbleoptiadapters/status
  verbs:
  - get
