---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - adapter.uri-tech.github.io
  resources:
  - nimbleoptis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - adapter.uri-tech.github.io
  resources:
  - nimbleoptis/finalizers
  verbs:
  - update
- apiGroups:
  - adapter.uri-tech.github.io
  resources:
  - nimbleoptis/status
  verbs:
  - get
  - patch
  - update
