---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - nimbleoptiadapter.nimble-opti-adapter.example.com
  resources:
  - nimbleoptiadapters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nimbleoptiadapter.nimble-opti-adapter.example.com
  resources:
  - nimbleoptiadapters/finalizers
  verbs:
  - update
- apiGroups:
  - nimbleoptiadapter.nimble-opti-adapter.example.com
  resources:
  - nimbleoptiadapters/status
  verbs:
  - get
  - patch
  - update
