apiVersion: config.nimbleopticadapter.tech-ua.com/v1alpha1
kind: NimbleOpticAdapterConfig
metadata:
  labels:
    app.kubernetes.io/name: nimbleopticadapterconfig
    app.kubernetes.io/instance: nimbleopticadapterconfig-sample
    app.kubernetes.io/part-of: nimbleoptiadapter
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: nimbleoptiadapter
  name: nimbleopticadapterconfig-sample
spec:
  # TODO(user): Add fields here
