# ./helm/nimble-opti-adapterconfig/values.yaml

replicaCount: 1

image:
  repository: "urial1500/nimble-opti-adapter"
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

resources: {}
