# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nimbleopticadapterconfig.fullname" . }}
  labels:
    {{- include "nimbleopticadapterconfig.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nimbleopticadapterconfig.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nimbleopticadapterconfig.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}