---
# Create a namespace to logically separate our resources.
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-modify-ns
---
# Create a ServiceAccount which our CronJob will use to interact with the Kubernetes API.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-modify-sa
  namespace: ingress-modify-ns
---
# Create a ClusterRole that defines permissions to modify Ingress resources across all namespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-modify-role
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
# Bind our ServiceAccount to the ClusterRole, granting it the permissions defined above.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-modify-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-modify-role
subjects:
  - kind: ServiceAccount
    name: ingress-modify-sa
    namespace: ingress-modify-ns
---

