name: NimbleOptiAdapter_ci_main

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    # pull_request:
    #   branches: [ "main" ]
    # paths:
    #   # - "controllers/**"
    #   # - "Dockerfile"
    #   # - "main.go"
    #   - "*"
    #   # Exclude README.md from triggering the workflow
    paths-ignore:
      - "README.md"
      - "cronjob/**"
      - ".github/workflows/NimbleOptiAdapter_ci_cronjob.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check the repo.
        uses: actions/checkout@v3

      - name: Login to docker hub registry.
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_NOA_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_NOA_PASSWORD }}
        run: |
          docker login docker.io -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      # - name: Build and push "NimbleOptiAdapter".
      #   run: |
      #     IMAGE_TAG=$(date +%s)
      #     docker build ./NimbleOptiAdapter --file ./NimbleOptiAdapter/Dockerfile --tag urial1500/nimble-opti-adapter:$IMAGE_TAG --tag urial1500/nimble-opti-adapter:latest
      #     docker push urial1500/nimble-opti-adapter:$IMAGE_TAG
      #     docker push urial1500/nimble-opti-adapter:latest

      - name: Build and push "NimbleOpti".
        run: |
          IMAGE_TAG=$(date +%s)
          docker run --rm --privileged tonistiigi/binfmt --install all
          docker buildx create --use
          DOCKER_TARGET_PLATFORM="linux/arm64,linux/amd64"
          DOCKER_USERNAME="nimbleopti"
          DOCKER_IMAGE_NAME="nimble-opti-adapter"
          docker buildx build . --platform $DOCKER_TARGET_PLATFORM \
          --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
          --build-arg VCS_REF=$(git rev-parse --short HEAD) \
          --build-arg VERSION=0.1 \
          --tag $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$IMAGE_TAG --tag $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest  \
          --file ./Dockerfile \
          --output type=image,push=true
