name: NimbleOptiAdapter_ci_cronjob

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "cronjob/**"
      - "!cronjob/README.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check the repo.
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.20'

      - name: Run Go tests in cronjob directory
        run: |
          go test ./cronjob/... -count=1

      - name: Login to docker hub registry.
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_NOA_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_NOA_PASSWORD }}
        run: |
          docker login docker.io -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

      - name: Build and push "NimbleOpti".
        run: |
          IMAGE_TAG=$(date +%s)
          docker run --rm --privileged tonistiigi/binfmt --install all
          docker buildx create --use
          DOCKER_TARGET_PLATFORM="linux/arm64,linux/amd64"
          DOCKER_USERNAME="nimbleopti"
          DOCKER_IMAGE_NAME="cronjob-n-o-a"
          docker buildx build cronjob/ \
          --platform "$DOCKER_TARGET_PLATFORM" \
          --tag $DOCKER_IMAGE_NAME:$IMAGE_TAG --tag $DOCKER_IMAGE_NAME:latest \
          --file cronjob/Dockerfile \
          --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
          --build-arg VCS_REF=$(git rev-parse --short HEAD) \
          --build-arg VERSION=0.1 \
          --output type=image,push=true
